Revert "Renamed wrapper (#51)"
This reverts commit f43e380d6aa38c81da50ffe27c38796b3643cdab.

There are 2 test failures in the `master` branch:

    integration.JavaSourceVersion >
      specify_java_source_version_through_config FAILED

    integration.SanityCheckTest >
      executeJavaLibFixture FAILED

Reverting this commit puts the build back in a good state, and there's a
chance it also addresses codeclimate/codeclimate#827.

Before:

    codeclimate analyze -e sonar-java
    Starting analysis
    Running sonar-java: Done!
    error: (CC::CLI::Analyze::EngineFailure) engine sonar-java failed
    with status 99 and stderr
    engine produced invalid output: {:message=>"Invalid JSON",
    :output=>"INFO: Java 1.8.0_111-internal Oracle Corporation (64-bit)
    …

After:

    codeclimate analyze -e sonar-java
    Starting analysis
    Running sonar-java: Done!
    …
    Analysis complete! Found 76 issues.